---
name: CI/CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master

jobs:

  cancel_if_not_merged:
    name: Cancel Workflow if Pull Request is not merged
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Cancel Workflow Run
        run: gh run cancel ${{ github.run_id }} --repo ${{ github.repository }}

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Tag
        id: get-release-tag
        run: |
          echo "escaped-tag=$(echo $GITHUB_HEAD_REF | \
            cut -d'/' -f2 | \
            sed -r 's/\./\\\./g' \
           )" >> $GITHUB_OUTPUT

      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "\`\`\`json\n$GITHUB_CONTEXT\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Get Draft Release Metadata
        uses: cardinalby/git-get-release-action@v1
        id: get-draft-release-id
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          releaseNameRegEx: ^.*${{ steps.get-release-tag.outputs.escaped-tag }}.*$
          draft: true

      - name: Point Release at `main`
        run: |
          gh release edit ${{ steps.get-draft-release-id.outputs.tag_name }} \
           --target refs/heads/main \
           --repo ${{ github.repository }}

      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get-draft-release-id.outputs.id }}

      - name: Log Release ID
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo -e "Release ID: \`${{ steps.get-draft-release-id.outputs.id }}\`"
