---
name: Draft Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  draft_release:
    name: Draft Release
    if: |
      github.event.pull_request.draft == false &&
      startsWith(github.head_ref, 'release/')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  logging:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo -e "\`\`\`json\n$GITHUB_CONTEXT\n\`\`\`" >> $GITHUB_STEP_SUMMARY
