---
name: Enforce SemVer Label

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled

concurrency:
  group: enforce-label-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  enforce-semver-label:
    name: Enforce SemVer Label
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo -e "\`\`\`json\n$GITHUB_CONTEXT\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "major,minor,patch,hotfix,non-functional"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Include a SemVer or `non-functional` label"
