---
name: Enforce PR SemVer Label

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - auto_merge_enabled

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "major,minor,patch,hotfix,non-functional"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Include a SemVer or `non-functional` label"
