---
name: Test

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed
      - auto_merge_enabled
      - auto_merge_disabled

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        env:
          PR_LABELS_JSON: ${{ toJson(github.event.pull_request.labels.*.name) }}
          PR_LABELS: ${{ github.event.pull_request.labels.*.name }}
        run: |
          echo "$PR_LABELS_JSON"
          echo "$PR_LABELS"
